---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset: min

- name: Installing OS specific packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

- name: Configure Docker data directory
  ansible.builtin.include_tasks: configure_data.yml
  when: docker_data_dir != "/var/lib/docker"
