---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset: min

- name: Include OS specific packages when RedHat Distribution
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include OS specific packages for Ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

- name: Configure Docker data directory
  ansible.builtin.include_tasks: configure_data.yml
  when: docker_data_dir != "/var/lib/docker"
