# file: tasks/main.yml
---
- name: Installing OS specific packages
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker
...
