---
- name: Installing yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Setting distribution (rhel if RedHat or centos if AlmaLinux or default to ansible_distribution | lower)
  ansible.builtin.set_fact:
    distribution: "{{ 'rhel' if ansible_distribution == 'RedHat' else 'centos' if ansible_distribution == 'AlmaLinux' else ansible_distribution | lower }}"

- name: Debug distribution
  ansible.builtin.debug:
    msg: "{{ distribution }}"

- name: Adding signing key
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/{{ distribution }}/gpg"
    state: present

- name: Adding repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/{{ distribution }}/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ distribution }}/gpg"

- name: Installing packages
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Starting Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
